version: '3.8'
services:
  # 1. Your Application
  app:
    build: .
    container_name: sporty-event-tracker-app
    ports:
      - "8080:8080"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      APP_EXTERNAL_API_URL: http://localhost:8080/mock-api/score/
      APP_SCHEDULING_MODE: dynamic
      # ADD THIS: Limit Java to 256MB RAM
      JAVA_TOOL_OPTIONS: "-Xmx256m -Xms256m"
    depends_on:
      - kafka
      # kafka:
      # condition: service_healthy

  
  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    ports:
      - "9095:9094"
    environment:
      KAFKA_HEAP_OPTS: "-Xmx512M -Xms512M"
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      # CHANGE HERE: Advertise localhost:9095 to your laptop
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9095
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    healthcheck:
      # Internal check still uses 9092, so this line stays the same
      test: ["CMD-SHELL", "kafka-topics.sh --bootstrap-server localhost:9092 --list"]
      interval: 5s
      retries: 10