spring:
  application:
    name: sporty-event-tracker
  kafka:
    bootstrap-servers: localhost:9095
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8080

app:
  scheduling:
    mode: dynamic # Options: 'dynamic' (strict per-event) or 'global' (simple loop)
    fixed-rate: 10000 # 10 seconds
  kafka:
    topic: live-scores-topic
  external-api:
    url: http://localhost:8080/mock-api/score/
    

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} [TraceId:%X{correlationId}] [EventId:%X{eventId}] - %msg%n"
  level:
    com.sporty.eventtracker: DEBUG